// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdIb0dKlK-2gcjz9ZKU-nxLdfOcayyI5o',
    appId: '1:201752491845:web:deffd0aeaeaf861266b02c',
    messagingSenderId: '201752491845',
    projectId: 'my-lab-checkin-app-79',
    authDomain: 'my-lab-checkin-app-79.firebaseapp.com',
    storageBucket: 'my-lab-checkin-app-79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEBIlgw7TteWLvpq2sPUlxpH5GtQ7MjPA',
    appId: '1:201752491845:android:95be7a64875613ee66b02c',
    messagingSenderId: '201752491845',
    projectId: 'my-lab-checkin-app-79',
    storageBucket: 'my-lab-checkin-app-79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcfp136l-8dr2OFJq8xHLFtgg94cFpJ5g',
    appId: '1:201752491845:ios:173a13fe942f529466b02c',
    messagingSenderId: '201752491845',
    projectId: 'my-lab-checkin-app-79',
    storageBucket: 'my-lab-checkin-app-79.firebasestorage.app',
    iosBundleId: 'com.example.labTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcfp136l-8dr2OFJq8xHLFtgg94cFpJ5g',
    appId: '1:201752491845:ios:173a13fe942f529466b02c',
    messagingSenderId: '201752491845',
    projectId: 'my-lab-checkin-app-79',
    storageBucket: 'my-lab-checkin-app-79.firebasestorage.app',
    iosBundleId: 'com.example.labTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdIb0dKlK-2gcjz9ZKU-nxLdfOcayyI5o',
    appId: '1:201752491845:web:401bcecf09fbb8d066b02c',
    messagingSenderId: '201752491845',
    projectId: 'my-lab-checkin-app-79',
    authDomain: 'my-lab-checkin-app-79.firebaseapp.com',
    storageBucket: 'my-lab-checkin-app-79.firebasestorage.app',
  );
}
